#!/opt/pwn.college/python
options = FirefoxOptions(); options.add_argument("--headless")
service = FirefoxService(log_path="/dev/null")
browser = webdriver.Firefox(service=service, options=options)
atexit.register(browser.quit)

URL = "http://challenge.localhost:80/"; KEY = "pwn"

while True:
    try: browser.get(URL)
    except Exception: time.sleep(.5); continue


    try: WebDriverWait(browser,1).until(lambda d: d.execute_script(f"return localStorage.getItem('{KEY}')==='1337'"))
    except TimeoutException: time.sleep(.5); continue
    else:
        
        
        try: flag = open("/flag").read().strip()
        except Exception: flag = None
        
        
        if flag:
            try: requests.post(URL, data={"content": flag}, timeout=3)
            except Exception: pass
    time.sleep(1)
