#!/opt/pwn.college/python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import requests,urllib.parse,psutil,atexit,time,sys,os

os.environ.clear(); os.environ["PATH"]="/usr/bin:/bin"
if 80 not in {s.laddr.port for s in psutil.net_connections(kind="inet") if s.status=="LISTEN"}: sys.exit(1)

opts=Options(); opts.add_argument("--headless")
drv=webdriver.Firefox(service=Service(log_path="/dev/null"), options=opts)
atexit.register(drv.quit)
URL="http://challenge.localhost:80/"

while True:
    try: drv.get(URL)
    except Exception: time.sleep(.5); continue
    
    try: WebDriverWait(drv,1).until(EC.alert_is_present())
    except TimeoutException: time.sleep(.5); continue
    else:
        
        try: drv.switch_to.alert.accept()
        except Exception: pass
        
        try: flag = open("/flag").read().strip()
        except Exception: flag = None
        
        if flag:
            try: requests.post(urllib.parse.urljoin(URL, "/"), data={"content": flag}, timeout=3)
            except Exception: pass
    time.sleep(1)
